console.log('chdir: ', process.chdir)
console.log('config: ', process.config)
console.log('domain: ', process.domain)
console.log('platform: ', process.platform)
console.log('environment: ', process.env)
console.log('version: ', process.version)
console.log('cwd: ', process.cwd)
